[project]
src = "src"
out = "out"
dot_env = ".env"

[networks.pyevm]
is_zksync = false

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337
default_account_name = "anvil0"
unsafe_password_file = "/home/s3bc40/.moccasin/passwords/anvil0"

[networks.sepolia]
url = "https://ethereum-sepolia-rpc.publicnode.com"
chain_id = 11155111

[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true

[networks.contracts.counter]
deployer_script = "script/deploy_counter.py"


# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
